# Generated by Django 4.2.9 on 2024-03-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_nozze', '0003_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
