# Generated by Django 4.2.9 on 2024-03-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_nozze', '0004_item_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
    ]
