# Generated by Django 4.2.9 on 2024-03-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_nozze', '0005_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('salgo_al_rifugio', models.BooleanField()),
                ('dormo_al_rifugio', models.BooleanField()),
                ('numero_di_persone', models.PositiveIntegerField()),
            ],
        ),
    ]
