# Generated by Django 4.2.9 on 2024-03-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_nozze', '0006_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='comment',
            new_name='allergie',
        ),
        migrations.AddField(
            model_name='food',
            name='pesce',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vegetariano',
            field=models.BooleanField(default=False),
        ),
    ]
